# Generated by Django 5.0.1 on 2024-01-05 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CODMCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('ability', models.CharField(max_length=250)),
                ('affiliation', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CODMMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('terrain', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CODMPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(default=1)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CODMWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('damage', models.IntegerField()),
                ('fire_rate', models.FloatField()),
                ('ammo_capacity', models.IntegerField()),
                ('weapon_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CODMWeaponAssault',
            fields=[
                ('codmweapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CODM.codmweapon')),
                ('attachments', models.CharField(max_length=250)),
                ('recoil', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('CODM.codmweapon',),
        ),
        migrations.CreateModel(
            name='CODMWeaponKnives',
            fields=[
                ('codmweapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CODM.codmweapon')),
                ('throwable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('CODM.codmweapon',),
        ),
        migrations.CreateModel(
            name='CODMWeaponLMG',
            fields=[
                ('codmweapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CODM.codmweapon')),
                ('magazine_size', models.IntegerField()),
                ('suppression', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('CODM.codmweapon',),
        ),
        migrations.CreateModel(
            name='CODMWeaponShotgun',
            fields=[
                ('codmweapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CODM.codmweapon')),
                ('pellet_count', models.IntegerField()),
                ('spread_range', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=('CODM.codmweapon',),
        ),
        migrations.CreateModel(
            name='CODMWeaponSMG',
            fields=[
                ('codmweapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CODM.codmweapon')),
                ('attachments', models.CharField(max_length=250)),
                ('mobility', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('CODM.codmweapon',),
        ),
        migrations.CreateModel(
            name='CODMWeaponSniper',
            fields=[
                ('codmweapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CODM.codmweapon')),
                ('zoom_levels', models.IntegerField()),
                ('bolt_action', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('CODM.codmweapon',),
        ),
    ]
